### ISSUE TITLE
Pages loosing property assignments, except for special properties

### ISSUE THREAD

**Issue by kghbln** [WikiApiary/WikiApiary#114]
I am not sure about the cause but recently I see quite a lot of pages loosing their annotations for no obvious reason, e.g. [Stadtwiki Karlsruhe (fr)](https://wikiapiary.com/wiki/Special:Browse/Stadtwiki_Karlsruhe_%28fr%29). Thus they are disappearing from statistics. Another indicator is that the wiki is massively loosing its tracked website count, currently at 17K something, down from 19K something a fortnight ago. I do not know if it is connected but the re-factoring of the bees seems to correlate or a recent version of SMW?. Doing a full data refresh of the semantic store will help. Afterwards we can monitor if this happens again.

**Comment by jthingelstad** [comment]
This is super-weird and almost assuredly a bug in Semantic MediaWiki. The page you cite hasn't been updated since April 19. Triggering a "Refresh" on the page brings all the properties back. I did just update my Semantic MediaWiki code to current master as well.

The new bots do nothing but interface with the MediaWiki API, just like the current ones. It is hard to imagine them causing this. Plus, I shut them down and am running the old bots again as I work out bugs.

This Munin graph shows it very clearly.

![wikiapiary_active_websites-week](https://cloud.githubusercontent.com/assets/5351/3137822/68070230-e85e-11e3-9a68-675d5784d684.png)

![wikiapiary_segments-week](https://cloud.githubusercontent.com/assets/5351/3137826/76bc8b1a-e85e-11e3-8a20-43dc0d92d39b.png)

**Comment by jthingelstad** [comment]
I did trigger an edit on Template:Website, after having updated Semantic MediaWiki code to current master. I'll be curious to see if the template refresh causes this to correct itself.

**Comment by kghbln** [comment]
It seems so. :) However, which version of SMW was installed at the time this started to happen. Perhaps it is related to https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/297 which I was not able to test so far?

**Comment by mwjames** [comment]
Do you have current example of a page that lost its annotations? Is there a way to replicate the problem manually on WikiApiary, so that I could see for myself what's going on?

I don't think SemanticMediaWiki/SemanticMediaWiki#297 has something do to with the described issue.

**Comment by mwjames** [comment]
Could you setup a different instance with some samples from WikiApiary and run the bots that do edits for a period of time and see if we loose annotations on those pages.

If as [described](http://wikimedia.7.x6.nabble.com/Data-decay-Concerning-graph-tp5029273p5029331.html) annotations are lost due to edits we need to track what kind of edits or actions are causing the issue because currently no matter how I edit a page, annotations remain in place.

Currently you run 1.23.0-rc.1 which should be used on the test instance but in order to eliminate that MW has nothing to do with it, MW 1.22 should be tested with the same scenario.

**Comment by kghbln** [comment]
The problem observed by me is that the property annotations are lost without any edit. The page I used as an example (https://github.com/thingles/WikiApiary/issues/114#issue-34636299) was e.g. last edited in mid April but the loss of annotations only started to appear end of May. Touching the template helped bringing back the assignments, however the issue is still there since [this page](https://wikiapiary.com/wiki/Special:Browse/WikiHoster.net) recently lost its annotations.

@thingles What do you think?

**Comment by mwjames** [comment]
I reverted SemanticMediaWiki/SemanticMediaWiki/issues/303 for now from master which can be found in the `revert` branch. It would be good if you could switch to this branch and start to monitor the pages.

I know it is a pain but currently I have no clue in what causing the issue and betting on the reverted change because it was introduced as measurement against the Redirect issue in MW 1.23/1.24.

EDIT: If you switch to the branch without using composer, please remember to run `composer dump-autoload` to generate the autoloader file (normally generated when composer is run)

**Comment by kghbln** [comment]
I guess it will be nice to know when WikiAPIary started using the version containing change #303 to see if there is an immediate connection.

**Comment by mwjames** [comment]
#303 was merged May 7 and is currently the only commit I could think of that may explain the reported issue because all other commits in May (except #225) are related to tests only.

**Comment by kghbln** [comment]
I am not questioning this at all. However I observed this end of may for the first time, meaning that there is quite some gap until this started on the wiki. So knowing when this change rolled in at WikiAPIary will provide definite proof.

**Comment by jthingelstad** [comment]
I just updated to current master of Semantic MediaWiki. Also updated to the now released 1.23.0.

**Comment by mwjames** [comment]
> I just updated to current master of Semantic MediaWiki

I ask for using the `revert` branch not the master since the potential issue has been reverted not on master but on the `revert` branch.

The other issue is now that the MW master has changed which makes the analysis even more difficult as more than one variable has been altered (ceteris paribus) therefore 
- Use the SMW master with 1.23 0 and monitor the situation to ensure that symptoms still exists
- If symptoms still persists with 1.23.0 then switch to branch `revert`

**Comment by mwjames** [comment]
I don't have time to monitor this issue and as precautionary measure (as I have no idea on what is going) I will merge the `revert` branch into master which means the next time you update the master branch #303 is no longer included.

**Comment by jthingelstad** [comment]
Just updated again

```
  - Updating mediawiki/semantic-media-wiki dev-master (383d129 => 14061ca)
    Checking out 14061ca1f6368845cb795d9d846c60e11f8a516f
```

Note that this morning I just experienced another big drop in properties. 

![wikiapiary_segments-day](https://cloud.githubusercontent.com/assets/5351/3200506/2de1a262-ed7d-11e3-955c-2531aea3a8df.png)

again leaving only SESP and built-in SMW properties.

![screenshot](https://cloud.githubusercontent.com/assets/5351/3200516/52e69e5a-ed7d-11e3-899d-301bfe360a62.png)

There have been no edits to this page since April 17th. [history](https://wikiapiary.com/w/index.php?title=WikiApiary&action=history)

A refresh of the page [brings the properties back](https://wikiapiary.com/wiki/Special:Browse/WikiApiary).

**Comment by plexish** [comment]
Tracked count for websites, semantic websites, extensions, and a bunch of other stuff dropped suddenly earlier on. I figure it's this bug again?

**Comment by kghbln** [comment]
Indeed the revert of https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/303 did not help the cause since property decay is still an issue. A current example is the [1.22.7 page](https://wikiapiary.com/wiki/Special:Browse/Generator:MediaWiki_1.22.7).

**Comment by kghbln** [comment]
Since this page worked out fine this morning I can imagine only one cause: [The template "Generator"](https://wikiapiary.com/w/index.php?title=Template:Generator&action=history) was edited after that time. So my theory here is that the edit to the template causes the pages using it to refresh in a way that the property assignments are lost rather than being refreshed. I am predicting that all the other pages on generators will gradually loose their property annotations.

**Comment by jthingelstad** [comment]
See related SemanticMediaWiki/SemanticMediaWiki#347.

**Comment by jthingelstad** [comment]
Since applying the _work-around_ to manage this issue property counts have been stable. Very concerning issue, but at this point I think we can consider it resolved.

![screenshot](https://cloud.githubusercontent.com/assets/5351/3778372/50f03d3e-1971-11e4-8fac-0e7312ae93db.png)
