### ISSUE TITLE
Set $wgRestrictDisplayTitle to false

### ISSUE THREAD

**Issue by plexish** [WikiApiary/WikiApiary#128]
https://www.mediawiki.org/wiki/Manual:$wgRestrictDisplayTitle

Having this false would allow more descriptive titles for Extensions, Skins, Generators, and other things. Especially with hidenamespaces on (so a bunch of pages just have the title Main Page), this seems better. Also it would let me decapitalize my name on my user talk page without adding the User_talk: bit.

**Comment by jthingelstad** [comment]
It worries me a little that page names would be very different from display. @kghbln any thoughts on this?

**Comment by kghbln** [comment]
As far as I know this also breaks existing links to the pages with thus changed names though I am not absolutely sure. I think we should add a bit more text to the top of the page rather when doing basically the same by changing the display title.

However, [this](https://wikiapiary.com/wiki/Generator:Main_Page/OFFICIAL) page name is awful, so a move to something like "Gererator:Officially released generators" will be good. No need to change the display title here either. The current name does not work anyway since the generator namespace was not added to the array of [`$wgNamespacesWithSubpages`](https://www.mediawiki.org/wiki/Manual:$wgNamespacesWithSubpages) which is not really necessary either.

**Comment by jthingelstad** [comment]
FWIW I've added `$wgNamespacesWithSubpages[NS_GENERATOR] = true;` so subpages will work in that namespace. You know how I love subpages. :-)

**Comment by jthingelstad** [comment]
I’m going to close this as won't fix. I think the multiple pages named "Main Page" should be dealt with by simply giving them a better name. There is no requirement for "Generator:Main Page", it can be whatever we want it to be.

**Comment by plexish** [comment]
Fairly certain it does not break links (the URL stays the same, it only changes the displayed title?), but okay. Changing Main Page to something more descriptive will solve the real issue in a more intuitive way anyway (leaving only my poor capitalized talk page ;_;).

**Comment by kghbln** [comment]
You are in good company. kghbln vs Kghbln. ;)
