### ISSUE TITLE
Enable groups for Localization / Translation

### ISSUE THREAD

**Issue by jthingelstad** [WikiApiary/WikiApiary#165]
Via @kghbln:

> I saw that you put more effort into the translation of WikiAPIary. I think you still need to make regular users translators for them to use the interface. So far nothing shows up since there are no translators. I am curious to see how this will play with foreground. Let's hope for the best.

What groups do I need to setup?

**Comment by kghbln** [comment]
Well the user group "translator" is there, but nobody is assigned to it. I think a `$wgGroupPermissions['user']['translate'] = true;` is all we need here.

**Comment by jthingelstad** [comment]
@kghbln thank you. This is (finally) done.

**Comment by kghbln** [comment]
@thingles No worries. I just tried to make the whole main page translatable. Doing so I had to remove the userparam from the [template](https://wikiapiary.com/w/index.php?title=Template%3AWebsite_block%2FForeground&diff=1060231&oldid=243468) since we afaik cannot translate within a parserfunction. Have not removed it from the parserfunction to allow an easy revert. However, we should avoid mixing languages if possible.
