### ISSUE TITLE
Enable subpages on all content namespaces

### ISSUE THREAD

**Issue by plexish** [WikiApiary/WikiApiary#168]
I'd like to create some subpages of Host:Hosts with extra info, subpages being on would simplify a template and provide a link back to the base page.

Edit: Seems a few others are missing this. I'd like to do report pages everywhere, so if you're cool with using subpages of the main for reports I'd like them everywhere.

**Comment by kghbln** [comment]
Probably this was already done by @thingles upon set-up: Adding this namespace to the content namespaces for statistics

**Comment by plexish** [comment]
@kghbln When I use {{SUBPAGENAME}} on [Host:Hosts/Government](https://wikiapiary.com/wiki/Host:Hosts/Government) and similar pages it gives me Hosts/Government rather than Government, and the link back to base page is not automatically created. Unless something really strange is happening subpages are not enabled on Host:.

**Comment by kghbln** [comment]
@etesp I was only referring to 

> Adding this namespace to the content namespaces for statistics

I hijacked this issue :|

**Comment by plexish** [comment]
@kghbln Ah, right, sorry. I thought you were saying subpages was probably on already, missed the colon.

**Comment by plexish** [comment]
Farm: could do with this too, for [example](https://wikiapiary.com/wiki/Farm:Farms/Defunct).

Edit: Actually, let's just have this on all the content namespaces.

**Comment by jthingelstad** [comment]
Farm and Host namespaces now have subpages enabled.

I am not enabling them on all content namespaces, most notable Extension and Skin because I’m pretty sure there are extensions and skins that use "/" as a valid part of their name. This is a problem and something we should figure out how to deal with since I’m pretty sure at some point Extension and Skin pages will want to have subpages.
