### ISSUE TITLE
Handle multilingual wikis running on one mediawiki instance

### ISSUE THREAD

**Issue by plexish** [WikiApiary/WikiApiary#173]
There are several duplicates now found which work like [this](https://wikiapiary.com/wiki/Heroes_Wiki_%28en%29) [pair](https://wikiapiary.com/wiki/Heroes_Wiki_%28pt%29), [and](https://wikiapiary.com/wiki/Anarchopedia_%28bs%29) [this](https://wikiapiary.com/wiki/Anarchopedia_%28hr%29) [trio](https://wikiapiary.com/wiki/Anarchopedia_%28sr%29). One mediawiki instance accessible from several subdomains.

Should we have something like an alternate main page url/alternate language/flag for multilingual wiki? Or something else?

**Comment by jthingelstad** [comment]
That already exists with [Template:Multisite](https://wikiapiary.com/wiki/Template:Multisite) (which exists for [Anarchopedia](https://wikiapiary.com/wiki/Anarchopedia)). I wouldn't consider these duplicates. I just added a /doc page for the multisite template to at least indicate what it’s for.

**Comment by plexish** [comment]
It seems slightly inefficient to have the bots collecting the same data multiple times and duplicates of everything, but there's not that many of them so I guess that's not much of an issue. I guess the check duplicate template needs to get more clever to deal with this.

**Comment by jthingelstad** [comment]
@etesp just to clarify, the bots aren't collecting duplicates. Those wikis are completely independent entities with different user bases. Using a wiki farm for languages is a common approach, but they are not clones of each other. Nearly every metric will be different.

One thing to watch out for using Founded Date as a duplicate check is that some wiki farmers will use a SQL dump to get their wikis started. I do this for my wikis. As a result, they seem to all have the same founded date but that is just because they are cloned from the same starting DB. I fixed my founding dates by hand for this. I’m guessing some language farms may do the same thing.

**Comment by plexish** [comment]
Those wikis have exactly the same edit count and active users/user graphs though, I added a check so they need to have both same founding date and same edit count specifically to avoid labelling forked wikis as duplicates. Unless something really strange is happening, they're the same mediawiki instance, not independent entities.
