### ISSUE TITLE
Skins wrongly identified as extensions

### ISSUE THREAD

**Issue by Contrafibularity** [WikiApiary/WikiApiary#176]
When I brought up an issue about conflicting names here - https://www.mediawiki.org/wiki/Thread:Extension_talk:Bootstrap/Extension:Bootstrap_vs_Extension:Bootstrap#Extension:Bootstrap_vs_Extension:Bootstrap_45716 - Stephan Gambke pointed out to me that WikiApiary has been having problems with the registration of some skins. Apparently a number of them are recognised as extensions by mistake. Is the fact that some skins now use 'require once()' in Localsettings.php (and end up being listed in Special:Version) somehow responsible for this?

Stephan had sent an e-mail about this but I could not find a report in this venue, so there you go.

**Comment by jthingelstad** [comment]
Thanks. I did get a message via the WikiApiary feedback page from Stephan regarding this.

I do not see this as a bug. In these cases, the Skin is indeed registering an Extension by the same name. [Foreground](http://foreground.thingelstad.com/wiki/) does this as well.

See Foreground in [skins API call](https://wikiapiary.com/w/api.php?action=query&meta=siteinfo&siprop=skins&format=json) as well as in [extensions API call](https://wikiapiary.com/w/api.php?action=query&meta=siteinfo&siprop=extensions&format=json). 

Bootstrap does the same thing. See [skins API call](http://christopheducamp.com/wiki/api.php?action=query&meta=siteinfo&siprop=skins&format=json) and [extensions API call](http://christopheducamp.com/wiki/api.php?action=query&meta=siteinfo&siprop=extensions&format=json).

To me there isn't a bug, they both show up. Wether that is valid for them to show up there or not is a matter for MW core.

**Comment by jthingelstad** [comment]
Note [MW.org discussion related to this](https://www.mediawiki.org/wiki/Thread:Extension_talk:Bootstrap/Extension:Bootstrap_vs_Extension:Bootstrap).

**Comment by s7eph4n** [comment]
Hm, difficult.

It seems, that the API call just returns everything contained in $wgExtensionCredits. So you could argue, that in the end it is the skin developer's fault for putting the skin into that array.

Then again this is the only possibility to include credits for skins and recommended by https://www.mediawiki.org/wiki/Skinning#Boilerplate_and_definitions

So, how can we avoid mixing skins and extensions?
And more generally, what is Wikiapiary's concept of disambiguating non-identical extensions with identical names?

**Comment by kghbln** [comment]
A way will will perhaps be to take the `$type` info and check on this. However, there are extensions around using multiple types. Only a few but there are out there. I guess avoiding too generic nameing for extensions will be a solution too, e.g. "Bootstrap Frontend Provider" extension instead of "Bootstrap"  extension or whatever creativity tells.

**Comment by jthingelstad** [comment]
I think the solution to this has to be disambiguation. Invalidating some extensions as not really extensions seems dangerous. And, undoubtedly we already have duplicate extension names. I’m not sure of a good solution to disambiguation yet. Open to suggestions.

**Comment by s7eph4n** [comment]
Maybe it would be possible to distinguish them using the URL field?

**Comment by zaori** [comment]
To clarify, since this is still open - skins _are_ extensions. That is literally what they are with relation to MediaWiki. If you want to separate them out, however, they are a specific type of extension, and up-to-date ones should be properly marked as such. But it should also be noted that some may fall under other categories as well depending on their functionality, such as if they come with their own parser funtions etc.

**Comment by s7eph4n** [comment]
Well, yes and no. From a technical point of view I agree with you 100%. But from a users perception they are not. A user does not care about MW interna. They just come to WikiApiary to find some nice skin.
Or - the other way around - they come to WikiApiary to find out on which wikis the Bootstrap extension is used on and find the usage of the Bootstrap _skin_ (while all the time at says Bootstrap extension in the page title). See https://wikiapiary.com/wiki/Extension:Bootstrap.

There's certainly not an easy solution, not least because of the problem of overlapping functionalities you pointed out. Maybe a first step to solve this might be to find a way to properly disambiguate extensions/skins of the same name, e.g. using their source repo address.

**Comment by zaori** [comment]
Doesn't matter. This isn't about technical or user points of view, because if they're going to understand either, they'll need to understand both skins and extensions. Either users will already have the technical point of view (which is likely considering the nature of wikiapiary), or it won't mean anything to them anyway.

And at that point the only thing that's apt to help them would just be making the types or tags more prominent in some way.

I do agree it's an issue when extensions and skins have the same name, but I'd argue that that's just the point where someone needs to be smacked.

**Comment by s7eph4n** [comment]
> This isn't about technical or user points of view, because if they're going to understand either, they'll need to understand both skins and extensions.

Agreed. That's also why there never was a _Skin_ namespace on mw.org. Everybody looking for a skin for their wiki already knows, that they are really only looking for an extension.

> I do agree it's an issue when extensions and skins have the same name, but I'd argue that that's just the point where someone needs to be smacked.

Sounds good. And if it doesn't fix the problem the first time, smacking harder is always an option.

**Comment by jthingelstad** [comment]
Closing this issue as there is nothing for WikiApiary and Bumble Bee to do differently.
