### ISSUE TITLE
Upgrade Foreground skin to most recent master version

### ISSUE THREAD

**Issue by jthingelstad** [WikiApiary/WikiApiary#203]
A number of improvements have been made and features added.

**Comment by jthingelstad** [comment]
This is updated using the `develop` branch. For some reason I can’t get the logo to appear in the navbar. Need to bug @hutchy68 about that. :-)

**Comment by Hutchy68** [comment]
Ha! Bug away :smile:

You are missing a `'navbarIcon' => true,` because the default is false.

What you have...

```
$wgForegroundFeatures = array(
  'showActionsForAnon' => true,
  'NavWrapperType' => 'divonly',
  'showHelpUnderTools' => true,
  'showRecentChangesUnderTools' => true,
  'IeEdgeCode' => 1,
  'showFooterIcons' => true,
  'addThisFollowPUBID' => 'ra-5407bddd55dceeb5'
);
```

I saw you have the logo set, are you using it? I think you should use a single bee. Like this image I cropped and flipped. I'm uploading here. :smile:

![wikiapiarybee](https://cloud.githubusercontent.com/assets/3527469/4144666/fd38c758-33e5-11e4-9b89-6329f2d7e38d.png)

**Comment by jthingelstad** [comment]
Thanks @Hutchy68! Works good. We need to update the docs for Foreground to show that feature.

Also, https://github.com/thingles/wiki-farm/commit/04457a91d406f271b855ee6c8657c6383a38211f.

**Comment by Hutchy68** [comment]
Yes yes! I need to practice what I preach. 😄
