### ISSUE TITLE
Different skin name translations mistaken for different skins

### ISSUE THREAD

**Issue by mormegil-cz** [WikiApiary/WikiApiary#206]
WikiApiary lists a huge amount of skins, however, some of those are just different names for a single skin. E.g., both [Vector](https://wikiapiary.com/wiki/Skin:Vector) and [Vektor](https://wikiapiary.com/wiki/Skin:Vektor) refer to the [exact same skin](https://www.mediawiki.org/wiki/Skin:Vector), only “Vektor” is the name translated to a few other languages (and [Векторное](https://wikiapiary.com/wiki/Skin:%D0%92%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%BD%D0%BE%D0%B5) to yet others, etc.).

When WikiApiary queries MediaWiki API for skins in [RecordSkinsTask.run](https://github.com/WikiApiary/WikiApiary/blob/develop/apiary/tasks/website/skins.py#L18), it retrieves the skin names in the local language of the wiki, and use the localized name as the skin identifier, which leads to the above-mentioned problem.

An “ideal” solution might be to use `code` as the skin identifier, and map it to the relevant localized name, but that is probably overcomplicated for no real gain (WikiApiary is basically English-only, anyway).

A much simpler, yet completely satisfactory solution would be to include `siinlanguagecode=en` in the API query, so that the skin names are always returned in English. (I am not sure what would happen with the current skin data during the next bot run, e.g. would [Vektor](https://wikiapiary.com/wiki/Skin:Vektor) completely disappear, or would it need to be cleaned manually somehow, etc.)

**Comment by jthingelstad** [comment]
_This issue also discussed at [Template talk:Skin](https://wikiapiary.com/wiki/Template_talk:Skin#Need_support_for_translated_names)._

Thank you for the suggested solution @mormegil-cz! Apologies it took this long to implement but it is now in and has been running for nearly a day.

https://wikiapiary.com/w/index.php?title=Wikipedia_(ksh)/Skins&diff=2144203&oldid=1787534&rcid=&curid=27283

https://wikiapiary.com/w/index.php?title=Campaña_2.0_Venezuela/Skins&diff=2144259&oldid=2003180&rcid=&curid=86987

https://wikiapiary.com/w/index.php?title=저스트서버_위키/Skins&diff=2144181&oldid=1999738&rcid=&curid=87194

Bumble Bee has been doing these for almost 24 hours so should be complete soon.

This will take a while for Semantic MediaWiki to catch up and get all of its aggregate queries right. But the data should come to gather right soon enough.

Two things of note:
1. If you see a translated Vector or other skin name with 0 wikis using it, we should delete those.
2. You will see wikis that do not get updates because they are defunct or not answering. These old wikis will not get a fix for the translated name. The only way to fix that is to do a text replace on the wiki by hand, effectively doing what Bumble Bee has done by hand.

**Comment by nemobis** [comment]
>  include siinlanguagecode=en

Simple and effective! Thanks both.
