### ISSUE TITLE
Ciencia for ...

### ISSUE THREAD

**Issue by kghbln** [WikiApiary/WikiApiary#219]
[Ciencia](https://wikiapiary.com/wiki/Special:Contributions/Ciencia_Al_Poder) for editor, operator and admin :) Seen him on several spots the wikiverse were he makes a very good impression. Recently started to get involved with WikiApiary with great work

**Comment by ciencia** [comment]
Thanks :) although this recent activity boost is because of having more free time during holidays. I don't expect to spend that time normally. I usually check every new wiki I visit to see if it's already on wikiapiary to add them, when I found them in mediawiki.org's Support Desk or mediawiki freenode channel

Still, maybe the right to move pages without leaving a redirect behind would be useful to me

**Comment by jthingelstad** [comment]
Great! @ciencia [added to editor, operator and translator](https://wikiapiary.com/w/index.php?title=Special%3ALog&type=rights&user=&page=Ciencia+Al+Poder&year=&month=-1&hide_patrol_log=1&hide_thanks_log=1). No special reason to leave off admin. If needed please let me know!

**Comment by kghbln** [comment]
:)
