### ISSUE TITLE
Retrieve errorcount from Semantic MediaWiki API

### ISSUE THREAD

**Issue by jthingelstad** [WikiApiary/WikiApiary#228]
Per @mwjames:

> If you grab the information from the api `&errorcount` you could start to build a "semantic content health" or curation coefficient by comparing the error value relative to the overall property values of a wiki. A percentile base line can be used to mark a semantic wiki as "excellent", "good", "fair", "poor" in terms of curated values.

See SemanticMediaWiki/SemanticMediaWiki#893.

**Comment by kghbln** [comment]
Also have to decide what ratios may be called "excellent", "good", "fair" or "poor". < 0,1 %, < 0,5 %, < 1 %, > 1%?

**Comment by jthingelstad** [comment]
Bumble Bee is now collecting this data and putting it into the Apiary DB. Next step is to add a way to show it on a graph. I'll keep an eye on making sure it’s collecting right but so far looks great.

```
mysql> select website_id, capture_date, propcount, errorcount from smwinfo where errorcount > 0;
+------------+---------------------+-----------+------------+
| website_id | capture_date        | propcount | errorcount |
+------------+---------------------+-----------+------------+
| 18         | 2015-08-01 12:33:48 | 28892881  | 35         |
+------------+---------------------+-----------+------------+
1 rows in set (1.40 sec)
```

**Comment by jthingelstad** [comment]
Fun. Rolling in for more sites.

```
mysql> select website_id, capture_date, propcount, errorcount from smwinfo where errorcount >= 0;
+------------+---------------------+-----------+------------+
| website_id | capture_date        | propcount | errorcount |
+------------+---------------------+-----------+------------+
| 18         | 2015-08-01 12:33:48 | 28892881  | 35         |
| 19         | 2015-08-01 12:38:58 | 822498    | 1672       |
| 25         | 2015-08-01 12:40:59 | 89519     | 26         |
| 1062       | 2015-08-01 12:43:53 | 9775      | 2          |
| 1087       | 2015-08-01 12:42:29 | 3010      | 3          |
| 1183       | 2015-08-01 12:45:38 | 15429     | 0          |
| 13355      | 2015-08-01 12:40:16 | 3288      | 0          |
| 49761      | 2015-08-01 12:41:30 | 83576     | 0          |
| 87664      | 2015-08-01 12:41:56 | 449       | 0          |
| 166912     | 2015-08-01 12:43:26 | 963       | 0          |
| 171384     | 2015-08-01 12:40:37 | 1         | 0          |
+------------+---------------------+-----------+------------+
11 rows in set (1.52 sec)
```

**Comment by jthingelstad** [comment]
Now available in the graph dropdown on [WikiApiary](https://wikiapiary.com/wiki/WikiApiary).

![screenshot](https://cloud.githubusercontent.com/assets/5351/9022105/fef339e2-382c-11e5-9d08-fc6bd3ff2e61.png)

**Comment by jthingelstad** [comment]
Think this is now done.
- [Added to website template](https://wikiapiary.com/w/index.php?title=Template%3AWebsite&type=revision&diff=2144722&oldid=2096149)
- [Property:Has semantic error count](https://wikiapiary.com/wiki/Property:Has_semantic_error_count) created.
- Available as option in graphs.

If I missed anything let me know. Thank you for pointing this out @mwjames!

**Comment by kghbln** [comment]
> Also have to decide what ratios may be called "excellent", "good", "fair" or "poor". < 0,1 %, < 0,5 %, < 1 %, > 1%?

@thingles @mwjames
I have fluffed up the statistics page [on WikiAPIary](https://wikiapiary.com/wiki/Semantic_statistics/Errors) a bit. My guessed suggestion for classifying the annotation health of a semantic wiki seems to be pretty realistic as it turns out. Thoughts?

I am quite impressed to see so few errors on wikis. However we are seeing wikis here which obviously have good sysadmins and wiki gardeners (derived from the fact that these wikis were upgraded fast and run fairly recent versions of SMW)

**Comment by mwjames** [comment]
I like it because it shows SMW + Wiki can do more than just collecting facts, it can help to give some insights.

I don't want to sound smug but the name "https://wikiapiary.com/wiki/Semantic_statistics/Errors" indicates a strong connotation of a "blamable action", maybe have it renamed to something like Annotation health or smth.

You could have a top ten of the worst and "good" offenders while leaving the rest as further results (otherwise the list might become too long).

Maybe smw.org could have a page about "Improving annotation health" and a note to run `rebuildPropertyStatistics.php` on a regular basis to ensure that data displayed/gathered on wikiapiary are healthy as well (and linking from the wikiapiary page to smw.org).

**Comment by kghbln** [comment]
> I don't want to sound smug

That's the first that came to my mind too when I saw the list. I addressed this on the mailing list

> Maybe smw.org could have a page about "Improving annotation health"

The minimum will be to make people aware of the fact that something can be done to improve things.

**Comment by jthingelstad** [comment]
@mwjames @kghbln looking at this data point over time (now that it is being graphed!) has me a bit confused. Here is the graph for WikiApiary since started to collect (remember WikiApiary collects data every 15 mins).

![screenshot](https://cloud.githubusercontent.com/assets/5351/9059640/4c358aac-3a71-11e5-98f7-c2b12da7b1ff.png)

What is confusing to me is that I don't understand the changes that reduced the error count. As of now it’s at zero! Great, but I still see a large number of properties that have [improver values](https://wikiapiary.com/wiki/Property:Has_improper_value_for). Maybe I don't understand what the error count is actually telling me?

FYI, see [Property:Has statistic semantic annotation health](https://wikiapiary.com/wiki/Property:Has_statistic_semantic_annotation_health)

**Comment by kghbln** [comment]
Hmm, some kind of race condition or caching issue? As far as I can tell the wikis I control show the expected behaviour.

**Comment by mwjames** [comment]
Statistics are cached (including the error count) [0].

> has me a bit confused. Here is the graph for WikiApiary since started to collect (remember WikiApiary collects data every 15 mins).

Would you mind running `rebuildPropertyStatistics.php` to see whether this adjusts the value statement (because we access [1] to get the data).

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/SemanticMediaWiki.settings.php#L629-L630

[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/SQLStore/ListLookup/UsageStatisticsListLookup.php#L105-L109

**Comment by kghbln** [comment]
Yeah, 3600 secs - could have come up with this. On "my" wikis I do a day long caching and also rebuild the stats daily. Lets see what happens here. Touching wood. :)

**Comment by mwjames** [comment]
> That's the first that came to my mind too when I saw the list. I addressed this on the mailing list

Hope this helps [0,1].

[0] https://semantic-mediawiki.org/wiki/Help:Property_annotation_health
[1] https://semantic-mediawiki.org/wiki/Semantic_gardening

**Comment by mwjames** [comment]
> What is confusing to me is that I don't understand the changes that reduced the error count. As of now it’s at zero! 

I think the initial value started with a wrong baseline according to [0] as there are a lot more than 50.

Furthermore, I can see [0] contains removed entities (red linked). I just merged https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1100 (698ed00c) which hopefully should help with those but for this to work the red linked subjects need to be recreated (or undeleted) and deleted again to ensure that the `SMW_SQL3_SMWDELETEIW` marker is set.

[0] https://wikiapiary.com/w/index.php?title=Special:Ask&offset=0&limit=500&q=[[Has+improper+value+for%3A%3A%2B]]&p=format%3Dbroadtable%2Flink%3Dall%2Fheaders%3Dshow%2Fsearchlabel%3D...-20further-20results%2Fclass%3Dsortable-20wikitable-20smwtable&po=%3FHas+improper+value+for%0A&eq=yes

**Comment by kghbln** [comment]
> Hope this helps [0,1].

It does indeed. Added a bit more fluffy and now it is nice I guess. Thank you!

Another thing about annotation health: After @thingles added this coolness to the website page I realise that does not look good if a annotation health is 0 even though this is excellent. I figure that 100 is the better option. Also 99,87 % percent is probably less scary than 0,13 % so we should just reverse this.
